Initialization
epiphany-platform/m-host-init pull request #1
Opened 2021-03-09 15:18 UTC by mkyc

2021-03-10 10:14 UTC, to-bar requested changes

2021-03-10 10:14 UTC, to-bar commented on README.md
> +# m-host-init
IMO it would be nice to add just one sentence with information about purpose of this module 😉

2021-03-10 10:14 UTC, to-bar commented on cmd/apply.go
> +		}
Is it possible to get the function name from `err` instead of static value in `Msg`. Or this is by purpose since message can be different like in the last `if` ("ansible run failed").

2021-03-10 12:22 UTC, mkyc commented on Makefile
> +	@echo "$($*)"
that is true

2021-03-10 12:26 UTC, mkyc commented on README.md
> +# m-host-init
Ok, but I don't want to provide huge readme in this PR, so I'll add just very general sentence.

2021-03-10 12:38 UTC, mkyc commented on cmd/apply.go
> +		}
In general I like to have error messages as static as possible not to have "error in error" situations. Aside from this: 
 * we are in unnamed function passed to `Run func(cmd *Command, args []string)` parameter, so no name is known here
 * we get place of error on output because logger mechanism would provide it like following: 
   ```shell
   2021-03-10T12:35:48Z FTL go/src/github.com/epiphany-platform/m-host-init/cmd/apply.go:25 > checkAndLoad failed error="config file does not exist, please run init first"
   ```
 * static error messages allow to find related place in code easily

2021-03-10 13:41 UTC, atsikham commented on resources/project/roles/mounter/defaults/main.yml
> +  mountpoint: "/data/test1"
\n

2021-03-10 13:42 UTC, atsikham commented on resources/project/roles/mounter/handlers/main.yml
> +---
Can be removed

2021-03-10 13:42 UTC, atsikham commented on resources/project/roles/mounter/meta/main.yml
> +galaxy_info:
Do we need this file in such state?

2021-03-10 13:46 UTC, atsikham commented on resources/project/roles/mounter/vars/main.yml
> +---
Can be removed

2021-03-10 16:22 UTC, mkyc commented on Dockerfile
> +COPY --from=builder /entrypoint /workdir
I personally prefer to avoid `.` as much as possible. It introduces unexpected errors sooner or later.

2021-03-10 16:37 UTC, mkyc commented on resources/project/roles/mounter/.travis.yml
> +python: "2.7"
removed completely as we do not use travis

2021-03-10 16:37 UTC, mkyc commented on resources/project/roles/mounter/.travis.yml
> +  webhooks: https://galaxy.ansible.com/api/v1/notifications/
removed completely as we do not use travis

2021-03-10 16:59 UTC, mkyc commented on cmd/logger.go
> +package cmd
Yes, we do need it. It provides zerolog implementation to underlying dependency.

2021-03-10 17:00 UTC, mkyc commented on cmd/helpers.go
> +}
Yeah, this code is in each module so far. I didn't want to move it all to e-structures so it is here :)

2021-03-10 17:01 UTC, mkyc commented on cmd/init.go
> +	initCmd.Flags().String("vms_rsa", "vms_rsa", "name of rsa keypair to be provided to machines")
I was researching it some time ago and it looks that we should use `_` but I'm open for discussion. Anyways if that is what we want, we would need to do it in all modules and have it as design decision. We shouldn't do it in just one repository.

2021-03-10 17:11 UTC, mkyc commented on cmd/init.go
> +	initCmd.Flags().String("vms_rsa", "vms_rsa", "name of rsa keypair to be provided to machines")
AFAIU this helps with extensions ... but we provide here just name of keypair relative to `shared` directory. So it would break stuff.

2021-03-12 11:40 UTC, atsikham requested changes
Could you check Ansible configuration with `ansible-lint`? I would add names for all the tasks and split them by blank lines.

2021-03-12 11:40 UTC, atsikham commented on Dockerfile
> +COPY --from=builder /entrypoint /workdir
I can agree with that.

2021-03-12 11:40 UTC, atsikham commented on cmd/init.go
> +	initCmd.Flags().String("vms_rsa", "vms_rsa", "name of rsa keypair to be provided to machines")
Agree with following the standard for other modules, but I would prefer `-` even if it requires changes in all modules.

2021-03-12 11:40 UTC, atsikham commented on resources/project/roles/mounter/tasks/main.yml
> +    path: "/dev/disk/azure/scsi1/lun{{ vol.lun }}"
Is it only for Azure?

2021-03-12 11:40 UTC, atsikham commented on resources/project/roles/mounter/tasks/main.yml
> +    stt.stat.exists is defined and stt.stat.exists and
Is there a case when `stt.stat.exists` is undefined?

2021-03-12 11:40 UTC, atsikham commented on resources/project/roles/mounter/tasks/main.yml
> +    stt.stat.islnk is defined and stt.stat.islnk
Is there a case when `stt.stat.islnk` is undefined?

2021-03-12 11:40 UTC, atsikham commented on resources/project/roles/mounter/tasks/main.yml
> +        di.partitions is defined and
Is there a case when `di.partitions` is undefined within this block?

2021-03-12 11:40 UTC, atsikham commented on resources/project/entrypoint.yml
> +      with_items: "{{ mountpoints }}"
I suggest changing it to `loop` as we do for other Ansible roles, discussed that one time with @to-bar

2021-03-12 15:03 UTC, mkyc commented on resources/project/roles/mounter/tasks/main.yml
> +    path: "/dev/disk/azure/scsi1/lun{{ vol.lun }}"
yes, that role is only prepared and tested on azure for now

2021-03-12 15:05 UTC, mkyc commented on resources/project/roles/mounter/tasks/main.yml
> +    stt.stat.exists is defined and stt.stat.exists and
hmmmmm .... probably not, but that is I believe good practice to "null check" ... but that is my personal opinion so I can remove it if you want.

2021-03-12 15:05 UTC, mkyc commented on resources/project/roles/mounter/tasks/main.yml
> +    stt.stat.islnk is defined and stt.stat.islnk
same here

2021-03-12 15:05 UTC, mkyc commented on resources/project/roles/mounter/tasks/main.yml
> +        di.partitions is defined and
same here

2021-03-12 15:20 UTC, mkyc commented on cmd/runner.go
> +	gar "github.com/mkyc/go-ansible-runner"
discussed separately

2021-03-12 17:25 UTC, atsikham approved these changes

2021-03-18 07:48 UTC, to-bar requested changes

2021-03-18 09:18 UTC, to-bar commented on cmd/helpers.go
> +	cmdlineFilePath := filepath.Join(ResourcesDirectory, envDir, cmdlineFile)
Do we need to store these options in file? I had strange behavior after running `plan` action first, then `apply`. The first action created /resources/env/cmdline created with content `--check --diff` and the `apply` action didn't work well (partition was not created). The message was `Running command ansible-runner with args [run . --ident 20210318-091223 --playbook entrypoint.yml -vv]` so I was not aware that this is still the check mode.
I had to remove `/resources/env/cmdline`, then partition was created.

2021-03-22 10:53 UTC, mkyc commented on Dockerfile
> +# TODO change source image to be able to change user (additional context: https://github.com/ansible/ansible-runner/issues/611)
issue #3 created

2021-03-22 11:05 UTC, mkyc commented on cmd/helpers.go
> +		err = ioutil.WriteFile(backupPath, input, 0644)
TBH I don't think it's important at all. But I added it to [this issue](https://github.com/epiphany-platform/e-structures/issues/6) to consider it when doing it.

2021-03-22 11:29 UTC, mkyc commented on cmd/helpers.go
> +		vars["mountpoints"] = mountPoints
I don't feel same way. Putting single `for` into with single instruction into separate function looks like creation of artificial value.

2021-03-22 12:16 UTC, mkyc commented on cmd/init.go
> +	Run: func(cmd *cobra.Command, args []string) {
This function itself is not Azure specific but pointed part definitely is related to previously expected AzBI module. So I extracted this part into separate function as you proposed.

2021-03-22 12:47 UTC, mkyc commented on cmd/root.go
> +	rootCmd.PersistentFlags().IntVarP(&ansibleDebugLevel, "ansible_debug_level", "a", 0, "set ansible debug level 0-6")
ad 1.: There is already #2 created. 
ad 2.: I assume we would change `--debug` into `--logLevel` soon as in other repos, and then `-l` is good short for that. I like `-a` in here. It's very clear distinction from module log level itself.

2021-03-22 12:49 UTC, mkyc commented on cmd/runner.go
> +	options := gar.Options{
Nope. That is Golang auto formatter.

2021-03-22 12:50 UTC, mkyc commented on cmd/init.go
> +	initCmd.Flags().String("vms_rsa", "vms_rsa", "name of rsa keypair to be provided to machines")
Same as previously. There is #2 already created.

2021-03-22 12:53 UTC, mkyc commented on resources/project/roles/mounter/defaults/main.yml
> +  mountpoint: "/data/test1"
Created #4

2021-03-22 12:54 UTC, mkyc commented on resources/project/roles/mounter/tasks/main.yml
> +    path: "/dev/disk/azure/scsi1/lun{{ vol.lun }}"
Ok ... and?

2021-03-22 13:04 UTC, mkyc commented on resources/project/roles/mounter/tasks/main.yml
> +    luns: "{{ luns | default({}) | combine( { vol.lun : { stt.stat.lnk_source + '1' : vol.mountpoint } } ) }}"
I don't want to introduce this change. I believe this should be work done when this role is being polished. It's kind of first impression of role and I don't want to spend time on this in here. I created #5 to address it later when we will focus on role itself.

2021-03-22 13:24 UTC, mkyc commented on cmd/helpers.go
> +	cmdlineFilePath := filepath.Join(ResourcesDirectory, envDir, cmdlineFile)
Created #6 for this comment.

2021-03-22 13:56 UTC, mkyc commented on .gitignore
> +/resources/.ansible/
Created #8 for this comment.

2021-03-22 13:57 UTC, mkyc commented on resources/project/roles/mounter/tasks/main.yml
> +    path: "/dev/disk/azure/scsi1/lun{{ vol.lun }}"
Created #7 for this.

2021-03-23 12:12 UTC, to-bar commented on cmd/helpers.go
> +		vars["mountpoints"] = mountPoints
I really like small functions approach since functions have names, which may make code self-commented :heart_eyes:

When you have `for` block, without a comment for what it is, you must read and "interpret" all its lines to understand its role. However, In this particular case the `for` block is really small so I'm fine to keep it as is 😉

2021-03-23 12:52 UTC, to-bar requested changes

2021-03-23 12:52 UTC, to-bar commented on resources/project/roles/mounter/tasks/main.yml
> +- name: Set mountpoints pafct
```suggestion
- name: Set mountpoints fact
```

2021-03-23 14:01 UTC, to-bar approved these changes

2021-03-24 13:09 UTC, erzetpe commented on cmd/init.go
> +	st "github.com/epiphany-platform/e-structures/state/v0"
Maybe we can use something more descriptive here?

2021-03-24 13:43 UTC, erzetpe approved these changes

2021-03-24 16:00 UTC, mkyc commented on cmd/init.go
> +	st "github.com/epiphany-platform/e-structures/state/v0"
I believe it's good enough for now. If required it could be improved in future easily.

2021-03-24 16:01 UTC, merged